### ISSUE TITLE
Remove generated files from git

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ogcapi-routes#10]
There are several HTML and PDF files checked in to git. These are being automatically regenerated (even when no changes to the source document are being made!) and checked in.

These documents are available on docs.opengeospatial.org and links are provided in the README.md document.

Removing the generated files would also avoid "change" alert noise on the repository.

**Comment by ghobona** [comment]
https://github.com/opengeospatial/ogcapi-routes/commit/be515ee4f17714a577c1580222541fa22bffdf90

https://github.com/opengeospatial/ogcapi-routes/commit/8ba6d3745fc41324e047a156ffb6be32026da8f4
