### ISSUE TITLE
Additional cost functions

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-routes#13]
See #9 for background. Discussed in the SWG meeting on 2021-02-09.

APIs should be able to specify their own cost functions beyond the most common ones currently includes (duration and distance), e.g. risk level, environmental impact, elevation gain. We cannot enumerate all useful cost functions, so we should generate a general capability for APIs to advertise and support additional cost functions.

**Comment by jeffharrison** [comment]
Path forward on this Issue would follow what was discussed in May 11, 2021 SWG mtg for 'Mode'. 

Server would need to declare 'Preference' values and 'Mode' values. Server needs to specify which Mode or Preference is taken by default. 

Clemens P volunteered to generate Pull Request and SWG will discuss at next meeting.
