### ISSUE TITLE
Weight and Height restrictions naming issues; maxSpeed in request

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-routes#16]
The names of the requirements classes and their associated properties in routing requests for calculating routes for vehicles of a specific weight and height are confusing.

While a specific roadway might have restrictions on heights and weights which are aptly named `maxHeight` and `maxWeight`, what a routing request specifes is one particular height and/or weight which will be evaluated as passable or not for each way.

A `maxSpeed` property would also be useful in the routing request for the maximum speed that a vehicle can travel at (for calculating traveling times).

The requirements classes should say something like:

```
7.8. Requirements Class "Height restrictions"
Consider a specified vehicle height in meters against known height restrictions when computing the route.

The server SHALL support a member with the name "height" in the route definition in a
HTTP POST request to the path /routes with the following schema:
name: height
in: query
schema:
  type: number

The computed route SHALL be passable by vehicles with a height up to the value of "height" in meters.
```

```
7.9. Requirements Class "Load restrictions"
Consider a specified vehicle weight in meters against known weight restrictions when computing the route.

The server SHALL support a member with the name "weight" in the route definition in a
HTTP POST request to the path /routes with the following schema:

name: weight
in: query
schema:
  type: number

The computed route SHALL be passable by vehicles with a weight up to the value of "weight" in tons.
```

**Comment by jeffharrison** [comment]
Group discussion on this topic... "The terms maxHeight and maxWeight may have come from the perspective of a data set." also "For the API Request the proper term would be Height and Weight."

Valuable discussions and this Issue will need to be discussed amongst additional SWG members and potentially Routing Pilot sponsor reps.

**Comment by jerstlouis** [comment]
An additional reason why naming these parameters `weight` and `height` is that they could also be used for other purposes, such as fuel efficiency modeling for fuel cost or "most fuel efficient" route, and calculating accurate acceleration/deceleration time e.g. for    fastest route (mostly the weight, but potentially height could also be considered as contributing to air resistance).
