### ISSUE TITLE
References section 

### ISSUE THREAD

**Issue by jeffharrison** [opengeospatial/ogcapi-routes#2]
Complete References section.

Note: This issue applies to both

OGC API - Routes - Part 1: Core

and

OGC Route Exchange Model

**Comment by cportele** [comment]
The (normative) references in the Route Exchange Model should already be complete. We may add more informative references to the bibliography.

**Comment by jeffharrison** [comment]
Got it. Thanks!

**Comment by jeffharrison** [comment]
Content added to References section of OGC API - Routes.

**Comment by cportele** [comment]
Section in the Routing API has been updated in #20. Still open: REM.
