### ISSUE TITLE
Change resultSet to profiles?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-routes#21]
Requesting a Result Set is basically requesting a certain profile of a route. Since "profile" is a concept that is broadly used (see RFC 6906, the conneg-by-profile discussions in IETF/W3C, etc), should we replace the `resultSet` query parameter by a `profile` query parameter?

The `profile` parameter could be defined as an array so that this parameter could be used as an extension mechanism in the future?

If it happens that conneg-by-profile will be broadly used in practice, negotiating the result set could be done with standard web mechanisms.

**Comment by jeffharrison** [comment]
I took a look at RFC 6906 and some PROF-CONNEG documents... This is a very interesting suggestion.

Would be very curious to hear what others in Routes SWG think...

**Comment by jeffharrison** [comment]
16 June 2021 SWG Meeting discussed this. No rush to decide this Issue today since most of the open Issues are now resolved. 

Group agreed to consider this as a potential change over next two weeks.

**Comment by cportele** [comment]
Meeting 2021-12-09: Based on the results and discussions of the sprint, it was agreed to remove the resultSet requirements class from Core and address selective requests in a future extension. This should also look into re-use of existing building blocks for filtering features and paging.
