### ISSUE TITLE
Should duration be optional?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-routes#35]
Currently "duration" is, like "length", mandatory in the route overview and each route segment. This makes sense for length, since there is always a geometry. However, computing realistic durations may not always be necessary or straightforward. If we keep "duration" as a mandatory attribute, this will likely result in not-very-useful values in cases where a routing engine would normally not compute a duration (like a constant value multiplied by the length). It would be clearer to make the duration optional in the REM.

**Comment by skyNacho** [comment]
I've been thinking about this for a while to figure out whether duration is an inner property of a route or just optional. This is more about what the majority of people consider a route is, not what we might feel should be included. So I looked at the definitions in different languages:

- Cambridge dictionary: "A particular way or direction between places"
- Larousse dictionnaire: "Itinéraire à suivre pour se rendre d'un lieu à un autre"
- Real Academia Española: "Itinerario para el viaje. Carretera"

No definition mentions duration or time. The Spanish definition even considers it a synonym to road. I am now in favor of making it optional.

**Comment by cportele** [comment]
Meeting 2021-12-09: Make duration optional, but strongly recommend, to provide an estimated duration for each segment / the total route.
