### ISSUE TITLE
Req 4 Content-Language and mixed content

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-routes#38]
Requirement 4 F says:

> The response SHALL include a Content-Language header with the language used for instructions and **names, in particular road/street names**.

What if the response uses the default name, e.g. OSM `name` field, which is normally in the local language?
Even if the a particular language is preferred, not all streets may be available in a particular negotiated language, so there will likely always be mixed content of different language in street names of the response. Perhaps the expectation could be clarified to take that into account?

**Comment by cportele** [comment]
I agree. If an API can meet the requirement will depend on whether the underlying data source is multi-lingual or not. If it is, it makes sense to follow the approach described. If the data is not multi-lingual, it is not possible to meet the requirement as you point out. Should we change it to a recommendation (mainly for the cases where multi-lingual information is available) and explain the context?

**Comment by jerstlouis** [comment]
Yes, making it a recommendation and clarifying the context would make a lot of sense to me.

**Comment by cportele** [comment]
Meeting 2021-12-09: Agreement to implement the proposal.
