### ISSUE TITLE
Clarify that tons are metric tons

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-routes#41]
Reported by @skynacho:

https://docs.ogc.org/DRAFTS/21-000.html#rc_weight currently says:

> The computed route SHALL be passable by vehicles with a weight up to the value of "weight" in tons.

This is ambiguous as there are also short or long tons in addition to metric tons. "tons" should be changed to "metric tons".

**Comment by jerstlouis** [comment]
Probably best to spell it something like _tonne (metric ton)_ , i.e. 1 megagram (1000 kg,  ~2,204.6 lbs) to avoid any confusion?

https://wiki.openstreetmap.org/wiki/Key:maxweight says:

>  You must explicitly specify the unit if it is not in metric tonnes. 

> In most of the United States, weight restrictions are expressed in short tons (abbreviated as "tons", "T", or "t"), which should be tagged as maxweight=### st, and sometimes in pounds (abbreviated as "lbs"), which should be tagged as maxweight=### lbs, but never as metric tons. 

therefore I assume metric tonnes makes sense as the default.

**Comment by cportele** [comment]
Meeting 2021-12-09: Agreement to use "metric ton (tonne)".
