### ISSUE TITLE
Replace describedBy with describedby in REM

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-routes#46]
Replace `describedBy` with `describedby` in https://github.com/opengeospatial/ogcapi-routes/blob/master/rem/standard/clause_6_overview.adoc

**Comment by cportele** [comment]
@ghobona - Can you explain why? 

It is an object property in clause 6 and the usual convention is lowerCamelCase. If represented in the JSON encoding as a link, the link relation type will be "describedby" as specified [here](https://docs.ogc.org/DRAFTS/21-001.html#rec_rem_links), but that does not imply that "describedby" should be the property name in the Route model.

**Comment by ghobona** [comment]
@cportele Thanks for the clarification.

Withdrawing the suggestion.
