### ISSUE TITLE
Support for distance/cost calculation mode (no REM returned)

### ISSUE THREAD

**Issue by skyNacho** [opengeospatial/ogcapi-routes#9]
When computing **catchment areas**, the client needs to calculate route costs for a large amount of points, being performance a key factor. Building up the Route Exchange Model and sending it back to the client can reduce the performance by 20-50%.

Discuss whether this should be a use case supported by the Routing API core, an extension or something else.

As an example, Google offers its [distance matrix API](https://developers.google.com/maps/documentation/distance-matrix/overview) to cover this use case.

**Comment by skyNacho** [comment]
I have been working on catchment areas for the last week and tested a few concepts. Here are my conclusions to help making a decision:

* Is distance/cost calculation mode a relevant use case?

Yes. There are many applications interested not in routes themselves but in traveling costs (time, distance or others).

* Should this use case be supported by OGC API - Routes?

Actually, it is already supported (the Route Exchange Model includes the cost in distance and time in the route overview). The question is rather "would the performance improvement in an eventual distance/cost calculation mode justify the additional complexity of supporting this mode?", which does not have a straightforward answer. This is a relevant question as catchment area computation typically involve thousands or tens of thousands of route calculations, and performance is a key factor.

* Can we estimate the performance improvement if OGC API - Routes supports a distance/cost calculation mode?

Yes. I have worked on two options for a client requesting a route in a distance/cost calculation mode:

1) OGC API - Routes calculates the route but the response is just the route overview part of the Route Exchange Model. Exact times vary a lot depending on the route engine implementation, but my estimation is about 20% faster. For example, if a standard route calculation takes 0.5 seconds, with this mode it would take 0.4 seconds. So, if we need to calculate a 10,000-point catchment area calculation we save about 15 minutes in 1.5 hours. Not impressive.

2) OGC API - Routes calculates the route and the response is the route overview for the requested point, plus the route overviews of all the intersections on the way (that the routing engine had to calculate anyway). This is a great time savings but requires a more substantial change in the API and the data model. Using this approach for a 10,000-point catchment area calculation, the total time dropped from hours to minutes.

* How would OGC API - Routes fit in an overall architecture for this kind of use case? 

These applications require an intermediate service to receive the requests from the clients and to orchestrate the calculations (let's assume it is a generic WPS). If the routing engine belongs to the same provider exposing the WPS, then it is easiest to plug the routing engine directly to the WPS. Only if the routing engine belongs to a different provider we should consider adding support for distance/cost calculation mode.

So far, my conclusion is that it's probably best that OGC API - Routes focuses solely on routes and we do NOT add a specific support for distance/cost calculation mode. Eventually, there could be a separate API defined for distance/cost calculation, just the way Google is doing with its directions API vs distance matrix API, but that's out of scope at this moment. Any comments?

**Comment by cportele** [comment]
@skyNacho - Thanks for the analysis and feedback. I agree that an optimized batch cost calculation mode would either be a separate API or an extension that clearly would not belong to Part 1: Core.

**Comment by skyNacho** [comment]
@cportele thanks. If there are no more comments in the next call I will close this issue as solved.

**Comment by cportele** [comment]
Meeting 2021-02-09: We will close the issue, but there is still value in adding a new enum value to the resultSet list, e.g., "no-geometry". And there is a related topic that additional cost functions should be supported, e.g., risk. We cannot enumerate all useful cost function, so we should generate a general capability for APIs to advertise additional cost functions. New issues will be opened by @cportele to discuss this further.
